### ISSUE TITLE
Navbar zoom header bar

### ISSUE THREAD

**Issue by natbutter** [Sydney-Informatics-Hub/training-template#2]
When zooming in on the content the top nav bar gets big and takes up precious screen realestate. Can we pleas change the css to not increase or have a max-height of XX px or something?

**Comment by hlydecker** [comment]
Doesn't seem to be an issue in the current live build? Can you check and confirm @natbutter so I can close or fix it? 🤙

**Comment by natbutter** [comment]
Seems good.
